import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const root = '/Users/isaiahrivera/.agents';
const syncScript = path.join(root, 'sync.sh');

const runInFixtureHome = () => {
  const fixtureRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agents-adapter-fixture-'));
  const home = path.join(fixtureRoot, 'home');
  fs.mkdirSync(home, { recursive: true });

  execFileSync('bash', [syncScript, 'migrate'], {
    cwd: root,
    encoding: 'utf8',
    env: {
      ...process.env,
      HOME: home,
      HUB: root
    }
  });

  return { fixtureRoot, home };
};

test('sync migrate generates adapter outputs for opencode, antigravity, and openclaw', () => {
  const { fixtureRoot, home } = runInFixtureHome();

  try {
    const opencodeAgent = path.join(home, '.config/opencode/agents/analyst.md');
    const antigravityCommand = path.join(home, '.gemini/commands/implement_plan.toml');
    const antigravityAgent = path.join(home, '.gemini/agents/analyst.md');
    const antigravityGsd = path.join(home, '.gemini/get-shit-done/VERSION');
    const openclawAgents = path.join(home, '.openclaw/workspace/AGENTS.md');
    const openclawSoul = path.join(home, '.openclaw/workspace/SOUL.md');

    assert.ok(fs.existsSync(opencodeAgent));
    assert.ok(fs.existsSync(antigravityCommand));
    assert.ok(fs.existsSync(antigravityAgent));
    assert.ok(fs.existsSync(antigravityGsd));
    assert.ok(fs.existsSync(openclawAgents));
    assert.ok(fs.existsSync(openclawSoul));

    assert.match(fs.readFileSync(opencodeAgent, 'utf8'), /^---\nname: analyst\n/m);
    assert.match(fs.readFileSync(antigravityCommand, 'utf8'), /^description = /m);
    assert.match(fs.readFileSync(antigravityAgent, 'utf8'), /^---\n/m);
    assert.equal(fs.readFileSync(antigravityGsd, 'utf8').trim().length > 0, true);

    const openclawAgentsContent = fs.readFileSync(openclawAgents, 'utf8');
    const openclawSoulContent = fs.readFileSync(openclawSoul, 'utf8');
    assert.match(openclawAgentsContent, /Generated by ~\/\.agents\/sync\.sh/);
    assert.match(openclawAgentsContent, /\/Users\/isaiahrivera\/\.agents\/AGENTS\.md/);
    assert.match(openclawSoulContent, /IDENTITY\.md/);
  } finally {
    fs.rmSync(fixtureRoot, { recursive: true, force: true });
  }
});
